"""empty message

Revision ID: 104029fb01f7
Revises: 
Create Date: 2021-02-08 22:05:08.287741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '104029fb01f7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('articles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('create_time', sa.String(length=20), nullable=True),
    sa.Column('update_time', sa.String(length=20), nullable=True),
    sa.Column('cover', sa.Text(), nullable=True),
    sa.Column('title', sa.String(length=80), nullable=True),
    sa.Column('author', sa.String(length=10), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=15), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('images',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('create_time', sa.String(length=20), nullable=True),
    sa.Column('update_time', sa.String(length=20), nullable=True),
    sa.Column('title', sa.String(length=80), nullable=True),
    sa.Column('author', sa.String(length=10), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('desc', sa.Text(), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=15), nullable=True),
    sa.Column('manufacturer', sa.String(length=20), nullable=True),
    sa.Column('system_version', sa.String(length=20), nullable=True),
    sa.Column('cameral_model', sa.String(length=20), nullable=True),
    sa.Column('cameral_lens', sa.String(length=30), nullable=True),
    sa.Column('exposure_time', sa.String(length=10), nullable=True),
    sa.Column('iso', sa.Integer(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('length', sa.Integer(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('latitude_ref', sa.String(length=3), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('longitude_ref', sa.String(length=3), nullable=True),
    sa.Column('altitude', sa.Float(), nullable=True),
    sa.Column('altitude_ref', sa.String(length=3), nullable=True),
    sa.Column('position', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invitations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('create_time', sa.String(length=20), nullable=True),
    sa.Column('update_time', sa.String(length=20), nullable=True),
    sa.Column('code', sa.String(length=20), nullable=True),
    sa.Column('useable', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('questions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('create_time', sa.String(length=20), nullable=True),
    sa.Column('update_time', sa.String(length=20), nullable=True),
    sa.Column('ques_id', sa.Integer(), nullable=True),
    sa.Column('ques_type', sa.Integer(), nullable=True),
    sa.Column('ques_stem', sa.Text(), nullable=True),
    sa.Column('ques_option', sa.Text(), nullable=True),
    sa.Column('ques_right', sa.String(length=10), nullable=True),
    sa.Column('ques_analysis', sa.Text(), nullable=True),
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.Column('chapter_id', sa.Integer(), nullable=True),
    sa.Column('section_id', sa.Integer(), nullable=True),
    sa.Column('subject_name', sa.String(length=50), nullable=True),
    sa.Column('chapter_name', sa.String(length=50), nullable=True),
    sa.Column('section_name', sa.String(length=50), nullable=True),
    sa.Column('spent_time', sa.String(length=100), nullable=True),
    sa.Column('do_datetime', sa.String(length=200), nullable=True),
    sa.Column('right_times', sa.Integer(), nullable=True),
    sa.Column('starred', sa.Integer(), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('create_time', sa.String(length=20), nullable=True),
    sa.Column('update_time', sa.String(length=20), nullable=True),
    sa.Column('uid', sa.String(length=50), nullable=True),
    sa.Column('username', sa.String(length=32), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('avatar', sa.LargeBinary(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_table('questions')
    op.drop_table('invitations')
    op.drop_table('images')
    op.drop_table('articles')
    # ### end Alembic commands ###
